<?php

namespace Marando\JPLephem;

use \Marando\JPLephem\Results\Nutation;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-18 at 23:49:46.
 */
class EarthTest extends \PHPUnit_Framework_TestCase {

  /**
   * @covers Marando\JPLephem\Earth::position
   * @todo   Implement testPosition().
   */
  public function testPosition() {

    

    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\JPLephem\Earth::nutation
   */
  public function testNutation() {
    $nu = Earth::at(2446895.500000)->nutations();

    $this->assertEquals(-3.788 / 3600, $nu->longitude->deg, 'Δψ', 1e-3);
    $this->assertEquals(+9.443 / 3600, $nu->obliquity->deg, 'Δε', 1e-3);
  }

}
