<?php

namespace Marando\JPLephem;

use \Marando\JPLephem\DE\ElemNotFoundException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-18 at 23:49:46.
 */
class MoonTest extends \PHPUnit_Framework_TestCase {

  /**
   * @covers Marando\JPLephem\Moon::at
   * @todo   Implement testAt().
   */
  public function testAt() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\JPLephem\Moon::with
   * @todo   Implement testWith().
   */
  public function testWith() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\JPLephem\Moon::position
   * @todo   Implement testPosition().
   */
  public function testPosition() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\JPLephem\Moon::libration
   * @todo   Implement testLibration().
   */
  public function testLibration() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\JPLephem\Moon::mantleVelocity
   */
  public function testMantleVelocity() {
    $this->setExpectedException(ElemNotFoundException::class);
    $velocity = Moon::at(2451545.5)->mantleVelocity();
  }

}
