<?php

namespace Marando\JPLephem;

use \Marando\JPLephem\DE\ElemNotFoundException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-18 at 23:49:46.
 */
class SolarBaryTest extends \PHPUnit_Framework_TestCase {

  /**
   * @covers Marando\JPLephem\SolarBary::at
   * @todo   Implement testAt().
   */
  public function testAt() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\JPLephem\SolarBary::with
   * @todo   Implement testWith().
   */
  public function testWith() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\JPLephem\SolarBary::position
   * @todo   Implement testPosition().
   */
  public function testPosition() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\JPLephem\SolarBary::ttTDB
   */
  public function testTTtdb() {
    //$this->setExpectedException(ElemNotFoundException::class);

    //echo $ttTDB = SolarBary::at(2451545.5)->with('430t')->ttTDB();
    //echo $ttTDB = SolarBary::at(2552545.5)->with('430t')->ttTDB();
  }

}
