<?php

namespace Marando\JPLephem;

use \Marando\JPLephem\Results\CartesianVector;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-18 at 23:49:46.
 */
class SSObjTest extends \PHPUnit_Framework_TestCase {

  /**
   * Iterates through every planet combination and produces the coordinates
   */
  public function testAllPositions() {
    $jde     = 2457309.5;
    $planets = [
        SolarBary::at($jde),
        Sun::at($jde),
        Mercury::at($jde),
        Venus::at($jde),
        EarthBary::at($jde),
        Earth::at($jde),
        Moon::at($jde),
        Mars::at($jde),
        Jupiter::at($jde),
        Saturn::at($jde),
        Uranus::at($jde),
        Neptune::at($jde),
        Pluto::at($jde),
    ];

    foreach ($planets as $center) {
      foreach ($planets as $target) {
        if ($center == $target)
          continue;

        echo "\n{$center->name} -> {$target->name}";
        echo "\n------------------------------\n";
        echo $position = $center->position($target)->setUnit('AU, AU/d');

        $this->assertInstanceOf(CartesianVector::class, $position);
      }
    }
  }

}
