<?php

namespace Marando\JPLephem\DE;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-18 at 21:57:08.
 */
class DEConstTest extends \PHPUnit_Framework_TestCase {
  //----------------------------------------------------------------------------
  // Unit Tests
  //----------------------------------------------------------------------------

  /**
   * @covers Marando\JPLephem\DE\DEConst::count
   */
  public function testCount() {
    $const = new DEConst();

    $const->C22M   = 1;
    $const->ZD7    = 1;
    $const->RE     = 1;
    $const->TAUER2 = 1;

    $this->assertEquals(4, $const->count());
  }

  //----------------------------------------------------------------------------
  // Functional Tests
  //----------------------------------------------------------------------------

  /**
   * The purpose of this test is to see that values are the same when set and
   * retrieved
   */
  public function testValues() {
    $const = new DEConst();

    $const->C22M   = 1.32;
    $const->ZD7    = -14;
    $const->RE     = 1.32;
    $const->TAUER2 = 543.2;

    $this->assertEquals(1.32, $const->C22M);
    $this->assertEquals(-14, $const->ZD7);
    $this->assertEquals(1.32, $const->RE);
    $this->assertEquals(543.2, $const->TAUER2);
  }

}
