<?php

namespace Marando\JPLephem\DE;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-17 at 18:35:40.
 */
class DEHeaderTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var DEHeader
   */
  protected $header;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->header = new DEHeader(__DIR__ . '/header.421');
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    $this->header = null;
  }

  // // //

  public function testMeta() {
    // Before GROUP 1010
    $this->assertEquals(2036, $this->header->kSize);
    $this->assertEquals(1018, $this->header->nCoeff);
  }

  public function testGroup1010() {
    // GROUP 1010
    $this->assertEquals('JPL Planetary Ephemeris DE421/LE421',
            $this->header->description);
  }

  public function testGroup1030() {
    // GROUP 1030
    $this->assertEquals(2414992.50, $this->header->startEpoch);
    $this->assertEquals(2524624.50, $this->header->finalEpoch);
    $this->assertEquals(32, $this->header->blockSize);
  }

  public function testGroup1040() {
    // GROUP 1040
    $this->assertEquals(421, $this->header->const->DENUM, 'DENUM');
    $this->assertEquals(421, $this->header->const->LENUM, 'LENUM');
    $this->assertEquals(2.99792458e05, $this->header->const->CLIGHT, 'CLIGHT');
    $this->assertEquals(1.495978706996262e8, $this->header->const->AU, 'AU');
    $this->assertEquals(2.22910177219790600e-6, $this->header->const->ZDS, 'ZDS');
  }

  public function testGroup1050() {
    // GROUP 1050
    $cStart = [3, 171, 231, 309, 342, 366, 387, 405, 423, 441, 753, 819, 899];
    $cCount = [14, 10, 13, 11, 8, 7, 6, 6, 6, 13, 11, 10, 10];
    $cSets  = [4, 2, 2, 1, 1, 1, 1, 1, 1, 8, 2, 4, 4];
    $this->assertEquals($cStart, $this->header->coeffStart);
    $this->assertEquals($cCount, $this->header->coeffCount);
    $this->assertEquals($cSets, $this->header->coeffSets);
  }

}
