<?php

namespace Marando\JPLephem\DE;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-17 at 23:59:51.
 */
class DEreaderTest extends \PHPUnit_Framework_TestCase {

  /**
   * @covers Marando\JPLephem\DE\DEreader::interpPlanet
   * @todo   Implement testInterpPlanet().
   */
  public function testInterpPlanet() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\JPLephem\DE\DEreader::interp
   * @todo   Implement testInterp().
   */
  public function testInterp() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\JPLephem\DE\DEreader::testpo
   */
  public function testTestpo() {
    return;

    // Get the tests
    $de    = new DEreader(2451545);
    $tests = $de->testpo();

    $i = 0;
    foreach ($tests as $test) {
      // Skip non planet tests
      if ($test->center >= 10 || $test->target >= 10)
        continue;

      // Skip when Earth involved since it refers to the center not barycenter
      if ($test->center == 3 || $test->target == 3)
        continue;

      // Test values
      $jde    = $test->jde;
      $target = $test->target;
      $center = $test->center;
      $e      = $test->element - 1;

      // Interp coordinate
      $de     = new DEreader($jde);
      $t      = $de->interp($target, 3, true)[$e];
      $c      = $de->interp($center, 3, true)[$e];
      $result = round($t - $c, 15);



      if (abs($result - $test->value) > 1e-13)
        echo "{$jde}\t{$target}\t{$center}\n{$result}\n{$test->value}\n\n";

      if ($i == 50)
        break;

      $i++;
    }
  }

}
